import type { Client } from './types'

export const mockClients: Client[] = [
  {
    id: 'c1',
    initials: 'MR',
    name: 'María Rodríguez',
    routeId: 'r1',
    routeLabel: 'Ruta A · Centro',
    status: 'current',
    balance: 120_000,
    avatarColor: 'royal',
  },
  {
    id: 'c2',
    initials: 'JL',
    name: 'Juan López',
    routeId: 'r2',
    routeLabel: 'Ruta B · Norte',
    status: 'arrears',
    arrearsDays: 5,
    balance: 340_000,
    avatarColor: 'cyan',
  },
  {
    id: 'c3',
    initials: 'CG',
    name: 'Camila Gómez',
    routeId: 'r3',
    routeLabel: 'Ruta C · Sur',
    status: 'current',
    balance: 80_000,
    avatarColor: 'rust',
  },
  {
    id: 'c4',
    initials: 'RT',
    name: 'Ricardo Torres',
    routeId: 'r4',
    routeLabel: 'Ruta D · Occidente',
    status: 'new',
    balance: 250_000,
    avatarColor: 'green',
  },
  {
    id: 'c5',
    initials: 'AP',
    name: 'Andrea Patiño',
    routeId: 'r1',
    routeLabel: 'Ruta A · Centro',
    status: 'arrears',
    arrearsDays: 12,
    balance: 480_000,
    avatarColor: 'mint',
  },
  {
    id: 'c6',
    initials: 'LV',
    name: 'Luis Velásquez',
    routeId: 'r2',
    routeLabel: 'Ruta B · Norte',
    status: 'current',
    balance: 95_000,
    avatarColor: 'navy',
  },
]
